extends Node

const STOP_FORCE = 5000
const STOP_FORCE_ICE = 100

const RECOVER_STAMINA_TIME = 1
const RECOVER_STAMINA_TIME_TEMPERATURE = 2
const RECOVER_STAMINA_SPEED = 10.0
const RECOVER_STAMINA_SPEED_TEMPERATURE = 6.0
const EXHAUSTED_MULTIPLIER = 3